using System.Collections.Generic;

namespace INTERACTIVEMAP.Models
{
    public static class RoomData
    {
        public static List<RoomInfo> Rooms = new List<RoomInfo>
        {

            // --- FIRST FLOOR ---
        new RoomInfo { Id = "_002", Floor = "first", Name = "_002" },
        new RoomInfo { Id = "_003", Floor = "first", Name = "_003" },
        new RoomInfo { Id = "_004", Floor = "first", Name = "_004" },
        new RoomInfo { Id = "_007", Floor = "first", Name = "_007" },
        new RoomInfo { Id = "_008", Floor = "first", Name = "_008" },
        new RoomInfo { Id = "_009", Floor = "first", Name = "_009" },
        new RoomInfo { Id = "_014", Floor = "first", Name = "_014" },
        new RoomInfo { Id = "_015", Floor = "first", Name = "_015" },
        new RoomInfo { Id = "_017", Floor = "first", Name = "_017" },
        new RoomInfo { Id = "_019", Floor = "first", Name = "_019" },
        new RoomInfo { Id = "_020", Floor = "first", Name = "_020" },
        new RoomInfo { Id = "_022", Floor = "first", Name = "_022" },
        new RoomInfo { Id = "_022-2", Floor = "first", Name = "_022-2" },
        new RoomInfo { Id = "_023", Floor = "first", Name = "_023" },
        new RoomInfo { Id = "_024", Floor = "first", Name = "_024" },
        new RoomInfo { Id = "_025", Floor = "first", Name = "_025" },
        new RoomInfo { Id = "_026", Floor = "first", Name = "_026" },
        new RoomInfo { Id = "_027", Floor = "first", Name = "_027" },
        new RoomInfo { Id = "_038A", Floor = "first", Name = "_038A" },
        new RoomInfo { Id = "_038B", Floor = "first", Name = "_038B" },
        new RoomInfo { Id = "_038E", Floor = "first", Name = "_038E" },
        new RoomInfo { Id = "_038F", Floor = "first", Name = "_038F" },
        new RoomInfo { Id = "_039-2", Floor = "first", Name = "_039-2" },
        new RoomInfo { Id = "_039A", Floor = "first", Name = "_039A" },
        new RoomInfo { Id = "_041A", Floor = "first", Name = "_041A" },
        new RoomInfo { Id = "_041B", Floor = "first", Name = "_041B" },
        new RoomInfo { Id = "_041B-2", Floor = "first", Name = "_041B-2" },
        new RoomInfo { Id = "_046", Floor = "first", Name = "_046" },
        new RoomInfo { Id = "_047", Floor = "first", Name = "_047" },
        new RoomInfo { Id = "_048", Floor = "first", Name = "_048" },
        new RoomInfo { Id = "_049", Floor = "first", Name = "_049" },
        new RoomInfo { Id = "_050", Floor = "first", Name = "_050" },
        new RoomInfo { Id = "_051", Floor = "first", Name = "_051" },
        new RoomInfo { Id = "_052", Floor = "first", Name = "_052" },
        new RoomInfo { Id = "_053", Floor = "first", Name = "_053" },
        new RoomInfo { Id = "_053-2", Floor = "first", Name = "_053-2" },
        new RoomInfo { Id = "_054", Floor = "first", Name = "_054" },
        new RoomInfo { Id = "_056", Floor = "first", Name = "_056" },
        new RoomInfo { Id = "_062", Floor = "first", Name = "_062" },
        new RoomInfo { Id = "_063", Floor = "first", Name = "_063" },
        new RoomInfo { Id = "_064A", Floor = "first", Name = "_064A" },
        new RoomInfo { Id = "_064B", Floor = "first", Name = "_064B" },
        new RoomInfo { Id = "_066A", Floor = "first", Name = "_066A" },
        new RoomInfo { Id = "_066B", Floor = "first", Name = "_066B" },
        new RoomInfo { Id = "_066C", Floor = "first", Name = "_066C" },
        new RoomInfo { Id = "_067", Floor = "first", Name = "_067" },
        new RoomInfo { Id = "_069", Floor = "first", Name = "_069" },
        new RoomInfo { Id = "main_stairs", Floor = "first", Name = "main_stairs" },
        new RoomInfo { Id = "stairs", Floor = "first", Name = "stairs" },
        new RoomInfo { Id = "toilets", Floor = "first", Name = "toilets" },
        new RoomInfo { Id = "toilets_", Floor = "first", Name = "toilets_" },

            // --- SECOND FLOOR ---
        new RoomInfo { Id = "_002", Floor = "second", Name = "_002" },
        new RoomInfo { Id = "_003", Floor = "second", Name = "_003" },
        new RoomInfo { Id = "_004", Floor = "second", Name = "_004" },
        new RoomInfo { Id = "_007", Floor = "second", Name = "_007" },
        new RoomInfo { Id = "_008", Floor = "second", Name = "_008" },
        new RoomInfo { Id = "_009", Floor = "second", Name = "_009" },
        new RoomInfo { Id = "_014", Floor = "second", Name = "_014" },
        new RoomInfo { Id = "_015", Floor = "second", Name = "_015" },
        new RoomInfo { Id = "_017", Floor = "second", Name = "_017" },
        new RoomInfo { Id = "_019", Floor = "second", Name = "_019" },
        new RoomInfo { Id = "_020", Floor = "second", Name = "_020" },
        new RoomInfo { Id = "_022", Floor = "second", Name = "_022" },
        new RoomInfo { Id = "_023", Floor = "second", Name = "_023" },
        new RoomInfo { Id = "_024", Floor = "second", Name = "_024" },
        new RoomInfo { Id = "_027", Floor = "second", Name = "_027" },
        new RoomInfo { Id = "_038B", Floor = "second", Name = "_038B" },
        new RoomInfo { Id = "_038B-2", Floor = "second", Name = "_038B-2" },
        new RoomInfo { Id = "_038B-3", Floor = "second", Name = "_038B-3" },
        new RoomInfo { Id = "_038C", Floor = "second", Name = "_038C" },
        new RoomInfo { Id = "_038D", Floor = "second", Name = "_038D" },
        new RoomInfo { Id = "_038E", Floor = "second", Name = "_038E" },
        new RoomInfo { Id = "_038F", Floor = "second", Name = "_038F" },
        new RoomInfo { Id = "_038F-2", Floor = "second", Name = "_038F-2" },
        new RoomInfo { Id = "_038F-3", Floor = "second", Name = "_038F-3" },
        new RoomInfo { Id = "_038F-4", Floor = "second", Name = "_038F-4" },
        new RoomInfo { Id = "_039-2", Floor = "second", Name = "_039-2" },
        new RoomInfo { Id = "_039A", Floor = "second", Name = "_039A" },
        new RoomInfo { Id = "_040A-2", Floor = "second", Name = "_040A-2" },
        new RoomInfo { Id = "_041-2", Floor = "second", Name = "_041-2" },
        new RoomInfo { Id = "_041A", Floor = "second", Name = "_041A" },
        new RoomInfo { Id = "_041B", Floor = "second", Name = "_041B" },
        new RoomInfo { Id = "_046", Floor = "second", Name = "_046" },
        new RoomInfo { Id = "_047", Floor = "second", Name = "_047" },
        new RoomInfo { Id = "_048", Floor = "second", Name = "_048" },
        new RoomInfo { Id = "_049", Floor = "second", Name = "_049" },
        new RoomInfo { Id = "_050", Floor = "second", Name = "_050" },
        new RoomInfo { Id = "_051", Floor = "second", Name = "_051" },
        new RoomInfo { Id = "_052", Floor = "second", Name = "_052" },
        new RoomInfo { Id = "_053", Floor = "second", Name = "_053" },
        new RoomInfo { Id = "_053-2", Floor = "second", Name = "_053-2" },
        new RoomInfo { Id = "_054", Floor = "second", Name = "_054" },
        new RoomInfo { Id = "_056", Floor = "second", Name = "_056" },
        new RoomInfo { Id = "_062", Floor = "second", Name = "_062" },
        new RoomInfo { Id = "_064A", Floor = "second", Name = "_064A" },
        new RoomInfo { Id = "_066A", Floor = "second", Name = "_066A" },
        new RoomInfo { Id = "_066B", Floor = "second", Name = "_066B" },
        new RoomInfo { Id = "_066C", Floor = "second", Name = "_066C" },
        new RoomInfo { Id = "_067", Floor = "second", Name = "_067" },
        new RoomInfo { Id = "_069", Floor = "second", Name = "_069" },
        new RoomInfo { Id = "main_stairs", Floor = "second", Name = "main_stairs" },
        new RoomInfo { Id = "stairs", Floor = "second", Name = "stairs" },
        new RoomInfo { Id = "toilets", Floor = "second", Name = "toilets" },
        new RoomInfo { Id = "toilets_", Floor = "second", Name = "toilets_" },

            // --- THIRD FLOOR ---
        new RoomInfo { Id = "_002", Floor = "third", Name = "_002" },
        new RoomInfo { Id = "_003", Floor = "third", Name = "_003" },
        new RoomInfo { Id = "_004", Floor = "third", Name = "_004" },
        new RoomInfo { Id = "_007", Floor = "third", Name = "_007" },
        new RoomInfo { Id = "_008", Floor = "third", Name = "_008" },
        new RoomInfo { Id = "_009", Floor = "third", Name = "_009" },
        new RoomInfo { Id = "_014", Floor = "third", Name = "_014" },
        new RoomInfo { Id = "_015", Floor = "third", Name = "_015" },
        new RoomInfo { Id = "_017", Floor = "third", Name = "_017" },
        new RoomInfo { Id = "_019", Floor = "third", Name = "_019" },
        new RoomInfo { Id = "_020", Floor = "third", Name = "_020" },
        new RoomInfo { Id = "_021", Floor = "third", Name = "_021" },
        new RoomInfo { Id = "_022", Floor = "third", Name = "_022" },
        new RoomInfo { Id = "_022-2", Floor = "third", Name = "_022-2" },
        new RoomInfo { Id = "_023", Floor = "third", Name = "_023" },
        new RoomInfo { Id = "_024", Floor = "third", Name = "_024" },
        new RoomInfo { Id = "_025", Floor = "third", Name = "_025" },
        new RoomInfo { Id = "_026", Floor = "third", Name = "_026" },
        new RoomInfo { Id = "_027", Floor = "third", Name = "_027" },
        new RoomInfo { Id = "_038A", Floor = "third", Name = "_038A" },
        new RoomInfo { Id = "_038B", Floor = "third", Name = "_038B" },
        new RoomInfo { Id = "_038C", Floor = "third", Name = "_038C" },
        new RoomInfo { Id = "_038D", Floor = "third", Name = "_038D" },
        new RoomInfo { Id = "_038E", Floor = "third", Name = "_038E" },
        new RoomInfo { Id = "_038F", Floor = "third", Name = "_038F" },
        new RoomInfo { Id = "_039A", Floor = "third", Name = "_039A" },
        new RoomInfo { Id = "_039AO", Floor = "third", Name = "_039AO" },
        new RoomInfo { Id = "_040", Floor = "third", Name = "_040" },
        new RoomInfo { Id = "_040A-2", Floor = "third", Name = "_040A-2" },
        new RoomInfo { Id = "_040A-3", Floor = "third", Name = "_040A-3" },
        new RoomInfo { Id = "_040A-4", Floor = "third", Name = "_040A-4" },
        new RoomInfo { Id = "_041-2", Floor = "third", Name = "_041-2" },
        new RoomInfo { Id = "_041B", Floor = "third", Name = "_041B" },
        new RoomInfo { Id = "_046", Floor = "third", Name = "_046" },
        new RoomInfo { Id = "_048", Floor = "third", Name = "_048" },
        new RoomInfo { Id = "_049", Floor = "third", Name = "_049" },
        new RoomInfo { Id = "_050", Floor = "third", Name = "_050" },
        new RoomInfo { Id = "_050-2", Floor = "third", Name = "_050-2" },
        new RoomInfo { Id = "_051", Floor = "third", Name = "_051" },
        new RoomInfo { Id = "_052", Floor = "third", Name = "_052" },
        new RoomInfo { Id = "_053", Floor = "third", Name = "_053" },
        new RoomInfo { Id = "_053-2", Floor = "third", Name = "_053-2" },
        new RoomInfo { Id = "_054", Floor = "third", Name = "_054" },
        new RoomInfo { Id = "_056", Floor = "third", Name = "_056" },
        new RoomInfo { Id = "_062", Floor = "third", Name = "_062" },
        new RoomInfo { Id = "_063", Floor = "third", Name = "_063" },
        new RoomInfo { Id = "_064A", Floor = "third", Name = "_064A" },
        new RoomInfo { Id = "_064B", Floor = "third", Name = "_064B" },
        new RoomInfo { Id = "_066A", Floor = "third", Name = "_066A" },
        new RoomInfo { Id = "_066B", Floor = "third", Name = "_066B" },
        new RoomInfo { Id = "_066C", Floor = "third", Name = "_066C" },
        new RoomInfo { Id = "_067", Floor = "third", Name = "_067" },
        new RoomInfo { Id = "_069", Floor = "third", Name = "_069" },
        new RoomInfo { Id = "main_stairs", Floor = "third", Name = "main_stairs" },
        new RoomInfo { Id = "stairs", Floor = "third", Name = "stairs" },
        new RoomInfo { Id = "toilets", Floor = "third", Name = "toilets" },
        new RoomInfo { Id = "toilets_", Floor = "third", Name = "toilets_" },
        };
    }
}
